### ISSUE TITLE
Why does Mobile project need to be reloaded on first solution open?

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#365]
## Current behavior

We now get this everytime a Uno app solution is opened for the first time/created. Can we prevent it? It does not happen with MAUI, so it must be Uno specific

![image](https://github.com/unoplatform/uno.templates/assets/1075116/efaaee9f-b1ec-4a75-869e-241dc636655f)

## Expected behavior

No error

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment]
@dansiegel is investigating whether we can use an SDK to fix this. In meantime, this is fixed by https://github.com/unoplatform/uno.templates/pull/394

**Comment by jeromelaban** [comment]
This is not fixed entirely. We need to add some more properties to get this worked around properly.
