### ISSUE TITLE
WASM Multithreading feature does *nothing*

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#848]
There is a WASM Multithreading feature option in the wizard, but checking it has no effect on the generated project. Below is the screenshot of comparison of with and without:

![image](https://github.com/user-attachments/assets/86951a49-c573-4d96-9973-b6d6a9de26e0)

https://github.com/unoplatform/uno.templates/blob/d11a2e5f3777f118468433cc4d72e03da5c6123f/src/Uno.Templates/content/unoapp/.template.config/template.json#L691

**Comment by Jen-Uno** [comment]
Fixed with https://github.com/unoplatform/uno.templates/pull/865

**Comment by jeromelaban** [comment]
This issue is still valid, threading can still cause issues.
